#!/usr/bin/env node

/**
 * Module dependencies.
 */

// const util = require('./util');
const program = require('./commander');

program
  .command('comments', 'import comments')
  .parse(process.argv);

/**
 * When this process exists, check to see if we have a running command, if we do
 * check to see if it is still running. If it is, then kill it with a SIGINT
 * signal. This is for the use case where we want to kill the process that is
 * labeled with the PID written out by the parent process.
 */
process.once('exit', () => {
  if ((program.runningCommand.killed === false) && (program.runningCommand.exitCode === null)) {
    program.runningCommand.kill('SIGINT');
  }
});
