#!/usr/bin/env node

/**
 * Module dependencies.
 */

const program = require('./commander');

const Strategy = require('./services/strategy');
const Sponge = require('./services/sponge');

const mongoose = require('./services/talk/services/mongoose');

const Disqus = require('./services/disqus');

const util = require('./util');

const fs = require('fs');
const async = require('async');

// Register the shutdown criteria.
util.onshutdown([
  () => mongoose.disconnect()
]);

/**
* Import comments into the database.
*/
async function importComments(file) {
 
  // Get strategy the strategy use.
  const strategy = new Strategy(file);

  // Get the transformation tool going.
  const sponge = new Sponge(strategy.data);
  
  console.info('Importing comments from %s.', strategy.data.name);

  // Connect to disqus.  
  const disqus = new Disqus(strategy.data.service);

  let resolve = Promise.resolve();

  disqus.get_comments(strategy.data.service.forum)
  .then(posts => {
    for (let i in posts.response) {
      post = posts.response[i]

      resolve = resolve.then(() => {
        console.log(`Translating post ${post.raw_message}`);
        return sponge.translate(post, 'comments')
      })
      .catch((error) => {
        console.log(`Error on translating post. ${error}`)
      });
    }

    resolve.then(() => {
      console.log(`Success importing ${posts.response.length} comments for forum ${strategy.data.service.forum}.`);
      util.shutdown();
    })
    .catch((error) => {
      console.log('Error translating or importing comments. ', error);
      util.shutdown(1);
    });

  })
  .catch(error => {
    console.log('Error getting comments from Disqus. ', error);
    util.shutdown(1);
  });
}

//==============================================================================
// Setting up the program command line arguments.
//==============================================================================

program
  .command('import <file>')
  .description('import comments into database via strategy file')
  .action(importComments);

program.parse(process.argv);

// If there is no command listed, output help.
if (!process.argv.slice(2).length) {
  program.outputHelp();
  util.shutdown();
}
