#!/usr/bin/env node

const neo_disqus = require('neo-disqus')

const Source = require('./source');

class Disqus extends Source {
  constructor(service) {
    super();

    // Connect to disqus.  
    this.client = new neo_disqus({
      access_token: service.access_token,
      api_key: service.api_key,
      api_secret: service.api_secret
    })
  }

  find_comment(id) {
    const params = { post: id };
    return this.client.get("posts/details", params).then((result) => {
      return result.response;
    });

    // it needs to return post.response
  }

  get_comments(forum) {
    const params = { forum: forum , limit: 100};
    return this.client.get("forums/listPosts", params).then((result) => {
      return result.response;
    });

    // it needs to return only the response for each post in posts.
  }

  async get_asset(thread_id) {
    const params = {thread: thread_id}
    return this.client.get("threads/details", params).then((result) => {
      return result.response;
    });

    // it needs to return asset.response
  }
}

module.exports = Disqus;