#!/usr/bin/env node

class Source {
    constructor(service){
        this.service = service;
    }

    find_comment(commentid) {}
    get_comments(asset){}
    get_asset(asset_id){}
}

module.exports = Source;