#!/usr/bin/env node

const commentService = require('./talk/services/comments');
const userService = require('./talk/services/users');
const assetService = require('./talk/services/assets');
const actionService = require('./talk/services/actions');

const commentModel = require('./talk/models/comment');

class Talk {
    constructor(){
        console.log('Connecting to Talk API Client.');
    }

    findComment(id) {
        return commentService.findById(id)
        .then((c) => {
            return c;
        })
        .catch((error) => {
            console.log('Error when finding comment: ', error);
        });
    }

    findCommentByField(field, value) {
        return commentModel.findOne({field: value});
    }

    createComment(comment) {
        return commentService.publicCreate(comment)
        .then((c) => {
            return c;
        })
        .catch((error) => {
            console.log('Error when creating comment: ', error);
        });
    }

    // User needs {id, provider, displayName}
    // TODO: A decision needs to be made about the provider.
    createUser(user) {

        let id = user.id;
        let provider = user.provider;
        let displayName = user.displayName;

        return userService.findOrCreateExternalUser({id, provider, displayName});
    }

    // TODO: We need to automatically add the asset.url domain to the domain whitelist in Talk.
    createAsset(asset) {
        return assetService.findOrCreateByUrl(asset.url)
        .then((a) => {
            return a;
        })
        .catch((error) => {
            console.log('Error when creating asset: ', asset.url, error);
        });
    }

    createAction(action) {
        return actionService.insertUserAction(action)
        .then((a) => {
            return a;
        })
        .catch((error) => {
            console.log(`Error when creating action on ${action.item_id}: ${error}`);
        });
    }
}

module.exports = Talk;