#!/usr/bin/env node

class Comment {
    constructor(data) {
        this.data = data;
    }
}

      // console.log("id: ", post.id);
      // console.log("author: ", post.author);
      // console.log("message: ", post.message);
      // console.log("created at: ", post.createdAt);
      // console.log(post.parent);
      // console.log(post.isDeleted);
      // console.log(post.isApproved);
      // console.log(post.isFlagged);
      // console.log(post.isDeletedByAuthor);