#!/usr/bin/env node

class UserModel {
    constructor(data, source) {
        this.data = data;
        // this.username = data.username;
        // this.disable = false;
        // this.canEditName = true;
        // this.metadata = data.metadata;
        // this.createdAt = data.createdAt;

        // create a new profile for the specific source.
        // this.profiles
    }

    get(){
        return this.data;
    }
}

module.exports = UserModel;